### ISSUE TITLE
Ide konten mengenai Utility Types

### ISSUE THREAD

**Issue by Aldhanekaa** [bellshade/Typescript#15]
# Ide konten mengenai Utility Types pada TypeScript
halo semua, salam kenal. Jika saya perhatikan, tampaknya belum ada konten mengenai `utility types` di repo ini, dan saya menyarankan untuk menambahkannya!

setau saya Utility Types sendiri terbagi menjadi 3 bagian:
1. `Interface`
2. `type`
3. Utility Types itu sendiri (contoh: `Required<type>`)

terimakasih!

**Comment by Aldhanekaa** [comment]
Jika teman-teman berkenan, saya dapat mengerjakan mengenai konten `Interface` dan `type`.

**Comment by nomadkode** [comment]
> Jika teman-teman berkenan, saya dapat mengerjakan mengenai konten `Interface` dan `type` :))

tunggu tanggapan dari tim @bellshade/typescript-team dulu yaa sebaiknya gimana. kalo dah approve baru boleh assign ke diri sendiri. 👍🏼
